import type { DesignRulesState, WizardStep } from './types';

const STORAGE_KEY = 'mailcraft-studio-design-rules-v1';

export function getStorageKey(bundleId: string): string {
  return `${STORAGE_KEY}-${bundleId}`;
}

export const WIZARD_STEPS: WizardStep[] = [
  { id: 'brand', title: 'Brand identity', desc: 'Company name, taglines, and sender details' },
  { id: 'logo', title: 'Logo', desc: 'Logo URL, dimensions, and alt text' },
  { id: 'colors-core', title: 'Core colors', desc: 'Primary, secondary, and accent palette' },
  { id: 'colors-text', title: 'Text colors', desc: 'Headings, body, and muted text' },
  { id: 'colors-bg', title: 'Surfaces', desc: 'Backgrounds, sections, and dividers' },
  { id: 'colors-badge', title: 'Badges', desc: 'Event icons, steps, and promo highlights' },
  { id: 'buttons', title: 'Buttons & CTAs', desc: 'Primary, secondary, and link styles' },
  { id: 'typography', title: 'Typography', desc: 'Font stack and type scale' },
  { id: 'footer', title: 'Footer', desc: 'Address, social, and legal links' },
  { id: 'layout', title: 'Layout & spacing', desc: 'Width, padding, and radii' },
  { id: 'imagery', title: 'Imagery', desc: 'Image sizes and asset URLs' },
  { id: 'export', title: 'Review & export', desc: 'Checklist and download DESIGN_RULES.md' },
];

export const CHECKLIST_ITEMS = [
  'Logo URL loads over HTTPS',
  'Primary and secondary button colors meet contrast requirements',
  'Footer includes physical mailing address (CAN-SPAM)',
  'Unsubscribe link uses your ESP merge tag',
  'Support email is monitored',
  'Social and legal URLs are correct (or hidden if unused)',
  'Spot-check all 9 templates after applying brand changes',
];

export function getDefaultDesignRules(): DesignRulesState {
  const year = new Date().getFullYear();
  return {
    brandName: 'ForgeLine Industrial',
    legalName: 'ForgeLine Industrial, Inc.',
    tagline: 'Engineered for demanding environments',
    footerTrustLine: 'ISO 9001 certified • 24/7 field support • Nationwide parts delivery',
    copyrightNote: `©${year} ForgeLine Industrial *(set automatically when templates are generated)*`,
    fromName: 'ForgeLine Industrial',
    replyToEmail: 'support@forgeline-industrial.com',
    logoUrl: 'https://www.fmt.se/wp-content/uploads/2023/02/logo-placeholder-image.png',
    logoAlt: 'ForgeLine Industrial',
    logoWidth: '180px',
    logoHeight: 'auto',
    logoDarkUrl: '',
    faviconUrl: '',
    colorPrimary: '#1e40af',
    colorSecondary: '#2563eb',
    colorAccent: '#ea580c',
    colorHeadingDark: '#1f2937',
    colorHeadingAlt: '#1e293b',
    colorHeaderKicker: '#1a1a1a',
    colorBody: '#666666',
    colorBodyAlt: '#6b7280',
    colorMuted: '#64748b',
    colorBgEmail: '#ffffff',
    colorBgLightGray: '#f8fafc',
    colorBgInfo: '#e0e7ff',
    colorBgService: '#f0f9ff',
    colorBgServiceBorder: '#bae6fd',
    colorBgPromoDark: '#1e293b',
    colorBgWarning: '#fef3c7',
    colorBgWarningBorder: '#fbbf24',
    colorBgWarningText: '#92400e',
    colorBgUrgency: '#fef2f2',
    colorBgUrgencyBorder: '#fecaca',
    colorBgUrgencyText: '#dc2626',
    colorDivider: '#e5e5e5',
    colorFooterDivider: '#e2e8f0',
    colorBadgeEventBg: '#e0e7ff',
    colorBadgeEventText: '#1e40af',
    colorBadgeStepBg: '#fff7ed',
    colorBadgeStepText: '#ea580c',
    colorPromoHighlight: '#fbbf24',
    btnPrimaryBg: '#1e40af',
    btnPrimaryText: '#ffffff',
    btnPrimaryRadius: '8px',
    btnPrimaryPadding: '16px 32px',
    btnSecondaryBg: '#ffffff',
    btnSecondaryText: '#1e40af',
    btnSecondaryBorder: '#1e40af',
    btnPricingBg: '#1a1a1a',
    btnPricingText: '#ffffff',
    btnPromoBg: '#ea580c',
    btnPromoText: '#ffffff',
    linkColor: '#2563eb',
    urlBase: 'https://www.forgeline-industrial.com',
    urlQuote: '',
    urlSupport: '',
    fontStack: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    fontCustomUrl: '',
    fontCustomName: '',
    footerCompany: 'ForgeLine Industrial',
    footerAddress1: '2800 Industrial Parkway',
    footerAddress2: 'Cleveland, OH 44114',
    footerCountry: 'United States',
    footerEmail: 'support@forgeline-industrial.com',
    footerPhone: '',
    footerTagline: 'ISO 9001 certified • 24/7 field support • Nationwide parts delivery',
    footerTextColor: '#64748b',
    footerHeadingColor: '#1e293b',
    footerLinkColor: '#2563eb',
    socialFacebook: '',
    socialTwitter: '',
    socialInstagram: '',
    socialLinkedin: '',
    linkPrivacy: '',
    linkTerms: '',
    linkHelp: '',
    linkUnsubscribe: '{{unsubscribe_url}}',
    layoutMaxWidth: '600px',
    layoutOuterPadding: '20px 0',
    layoutSectionPadding: '40px 30px',
    layoutHorizontalPadding: '30px',
    layoutSpacerStandard: '24px',
    layoutSpacerLarge: '32–40px',
    layoutRadiusButtons: '8px',
    layoutRadiusHero: '12px',
    layoutRadiusGrid: '8px',
    imgHeroWidth: '600px (full bleed)',
    imgFeaturedWidth: '540px max',
    imgGridSize: '250 × 150px',
    imgThumbSize: '150 × 150px',
    imgHeroAspect: '3:2 or 16:9 landscape',
    imgHeroDefault: '',
    imgCdnBase: '',
    darkBgOverride: '',
    darkTextOverride: '',
    contrastTarget: '4.5:1 (body text)',
    checklist: CHECKLIST_ITEMS.map(() => false),
  };
}
