import type { DesignRulesState } from './types';
import { CHECKLIST_ITEMS } from './defaults';

function escMd(s: string | undefined | null): string {
  return String(s ?? '').replace(/\|/g, '\\|');
}

function val(s: string): string {
  return s ? s : '';
}

export function exportDesignRules(state: DesignRulesState): string {
  const d = state;
  const year = new Date().getFullYear();
  const copyright = d.copyrightNote.includes('{current year}')
    ? d.copyrightNote.replace('{current year}', String(year))
    : d.copyrightNote.replace(/\d{4}/, String(year));

  return `# Email Bundle: Design Rules

Define your baseline brand settings here before customizing templates. Generated by the Mailcraft Studio Brand Design Wizard.

> **How to use:** Fill in every section. When applying branding across templates, map each token to the matching \`data-element\` in the HTML (see *Element mapping* at the bottom).

---

## 1. Brand identity

| Field | Value |
|-------|-------|
| **Brand / company name** | ${escMd(d.brandName)} |
| **Legal entity name** *(if different)* | ${escMd(d.legalName)} |
| **Short tagline** | ${escMd(d.tagline)} |
| **Footer trust line** | ${escMd(d.footerTrustLine)} |
| **Copyright line** | ${escMd(copyright)} |
| **Default "From" name** *(email sender)* | ${escMd(d.fromName)} |
| **Default reply-to email** | ${escMd(d.replyToEmail)} |

---

## 2. Logo

| Field | Value |
|-------|-------|
| **Logo URL** | \`${escMd(d.logoUrl)}\` |
| **Logo alt text** | ${escMd(d.logoAlt)} |
| **Display width** | ${escMd(d.logoWidth)} |
| **Display height** | ${escMd(d.logoHeight)} |
| **Logo URL (dark background)** *(optional)* | ${escMd(val(d.logoDarkUrl))} |
| **Favicon / small mark URL** *(optional)* | ${escMd(val(d.faviconUrl))} |

**Notes**
- Use HTTPS-hosted PNG or JPG (SVG support varies in email clients).
- Keep file size under ~100 KB for deliverability.
- Transparent background recommended.

---

## 3. Color palette

### Core brand colors

| Token | Hex | Usage |
|-------|-----|-------|
| **Primary** | \`${d.colorPrimary}\` | Primary buttons, key links, icon badges, brand accents |
| **Secondary** | \`${d.colorSecondary}\` | Product CTAs, text links, footer legal links |
| **Accent** | \`${d.colorAccent}\` | Promotions, step numbers, highlight pricing |

### Neutrals & text

| Token | Hex | Usage |
|-------|-----|-------|
| **Heading dark** | \`${d.colorHeadingDark}\` | H1–H4, section titles |
| **Heading alt** | \`${d.colorHeadingAlt}\` | Hero titles, footer company name |
| **Header kicker** | \`${d.colorHeaderKicker}\` | Top-of-email kicker headlines |
| **Body text** | \`${d.colorBody}\` | Long-form body copy |
| **Body text alt** | \`${d.colorBodyAlt}\` | Descriptions, summaries |
| **Muted / subtitle** | \`${d.colorMuted}\` | Subtitles, captions, footer address |

### Backgrounds & surfaces

| Token | Hex | Usage |
|-------|-----|-------|
| **Email background** | \`${d.colorBgEmail}\` | Outer body and card |
| **Section: light gray** | \`${d.colorBgLightGray}\` | Pricing blocks, tier rows |
| **Section: info blue** | \`${d.colorBgInfo}\` | Insight callouts, download banners |
| **Section: service blue** | \`${d.colorBgService}\` | Service tier panels *(with border \`${d.colorBgServiceBorder}\`)* |
| **Section: promo dark** | \`${d.colorBgPromoDark}\` | Promo code / dark CTA bands |
| **Section: warning** | \`${d.colorBgWarning}\` | Important notes *(border \`${d.colorBgWarningBorder}\`, text \`${d.colorBgWarningText}\`)* |
| **Section: urgency** | \`${d.colorBgUrgency}\` | Limited-time alerts *(border \`${d.colorBgUrgencyBorder}\`, text \`${d.colorBgUrgencyText}\`)* |
| **Divider** | \`${d.colorDivider}\` | In-content section breaks |
| **Footer divider** | \`${d.colorFooterDivider}\` | Above footer block |

### Badge & icon colors

| Token | Hex | Usage |
|-------|-----|-------|
| **Event badge background** | \`${d.colorBadgeEventBg}\` | DATE / LOC / AUD icons |
| **Event badge text** | \`${d.colorBadgeEventText}\` | Event badge labels |
| **Step badge background** | \`${d.colorBadgeStepBg}\` | Numbered steps (enablement guide) |
| **Step badge text** | \`${d.colorBadgeStepText}\` | Step numbers |
| **Promo highlight text** | \`${d.colorPromoHighlight}\` | Promo codes on dark backgrounds |

---

## 4. Buttons & CTAs

### Primary button

| Field | Value |
|-------|-------|
| **Background** | \`${d.btnPrimaryBg}\` |
| **Text color** | \`${d.btnPrimaryText}\` |
| **Border** | none |
| **Border radius** | ${d.btnPrimaryRadius} |
| **Padding** | ${d.btnPrimaryPadding} |
| **Font size** | 16px |
| **Font weight** | 600 |

### Secondary button *(outline)*

| Field | Value |
|-------|-------|
| **Background** | \`${d.btnSecondaryBg}\` |
| **Text color** | \`${d.btnSecondaryText}\` |
| **Border** | 2px solid \`${d.btnSecondaryBorder}\` |
| **Border radius** | ${d.btnPrimaryRadius} |
| **Padding** | ${d.btnPrimaryPadding} |

### Text links *(inline, product cards)*

| Field | Value |
|-------|-------|
| **Color** | \`${d.linkColor}\` |
| **Decoration** | none |
| **Font weight** | 600 |

### Default CTA destination

| Field | Value |
|-------|-------|
| **Base website URL** | \`${escMd(d.urlBase)}\` |
| **Quote / contact URL** | ${escMd(val(d.urlQuote))} |
| **Support / help URL** | ${escMd(val(d.urlSupport))} |

---

## 5. Typography

| Field | Value |
|-------|-------|
| **Font stack** | \`${escMd(d.fontStack)}\` |
| **Custom web font URL** *(optional)* | ${escMd(val(d.fontCustomUrl))} |
| **Custom web font name** *(optional)* | ${escMd(val(d.fontCustomName))} |

---

## 6. Footer

| Field | Value |
|-------|-------|
| **Company name** | ${escMd(d.footerCompany)} |
| **Address line 1** | ${escMd(d.footerAddress1)} |
| **Address line 2** | ${escMd(d.footerAddress2)} |
| **Country** | ${escMd(d.footerCountry)} |
| **Support email** | ${escMd(d.footerEmail)} |
| **Support phone** *(optional)* | ${escMd(val(d.footerPhone))} |
| **Footer tagline** | ${escMd(d.footerTagline)} |
| **Footer text color** | \`${d.footerTextColor}\` |
| **Footer heading color** | \`${d.footerHeadingColor}\` |
| **Footer link color** | \`${d.footerLinkColor}\` |

### Social links

| Platform | URL |
|----------|-----|
| Facebook | ${escMd(val(d.socialFacebook))} |
| X (Twitter) | ${escMd(val(d.socialTwitter))} |
| Instagram | ${escMd(val(d.socialInstagram))} |
| LinkedIn | ${escMd(val(d.socialLinkedin))} |

### Legal & compliance links

| Link | URL |
|------|-----|
| Privacy Policy | ${escMd(val(d.linkPrivacy))} |
| Terms of Service | ${escMd(val(d.linkTerms))} |
| Help Center | ${escMd(val(d.linkHelp))} |
| Unsubscribe | \`${escMd(d.linkUnsubscribe)}\` *(ESP merge tag)* |

---

## 7. Layout & spacing

| Field | Value |
|-------|-------|
| **Email max width** | ${d.layoutMaxWidth} |
| **Outer padding** | ${d.layoutOuterPadding} |
| **Section padding** | ${d.layoutSectionPadding} |
| **Content horizontal padding** | ${d.layoutHorizontalPadding} |
| **Standard vertical spacer** | ${d.layoutSpacerStandard} |
| **Large vertical spacer** | ${d.layoutSpacerLarge} |
| **Border radius: buttons and cards** | ${d.layoutRadiusButtons} |
| **Border radius: hero product image** | ${d.layoutRadiusHero} |
| **Border radius: grid product images** | ${d.layoutRadiusGrid} |

---

## 8. Imagery

| Field | Value |
|-------|-------|
| **Hero image width** | ${d.imgHeroWidth} |
| **Featured product width** | ${d.imgFeaturedWidth} |
| **Grid product size** | ${d.imgGridSize} |
| **Horizontal catalog thumb** | ${d.imgThumbSize} |
| **Preferred hero aspect** | ${d.imgHeroAspect} |
| **Default hero image URL** *(placeholder)* | ${escMd(val(d.imgHeroDefault))} |
| **Image CDN / asset base URL** | ${escMd(val(d.imgCdnBase))} |

---

## 9. Template-specific notes

| Template | Notes |
|----------|-------|
| \`01_Product_Launch\` | Feature list: **left-aligned**. Pricing CTA uses dark button. |
| \`02_Product_Update\` | Numbered feature icons (01, 02, 03). Dual CTAs: primary + outline. |
| \`03_Products_Horizontal\` | Text links only (no filled buttons per row). |
| \`04_Products_Catalog_Grid\` | Divider between featured hero and product grid. |
| \`05_Event_Invitation\` | Icon badges: DATE, LOC, AUD. |
| \`06_Service_Launch\` | Feature list: **left-aligned**. Service tier panel uses info blue. |
| \`07_Product_Enablement_Guide\` | Orange step badges. Download banner uses info blue. |
| \`08_Promotion\` | Dark promo band + orange accent button. Tier rows on light gray. |
| \`09_Company_Update\` | Company Highlights: **left-aligned**. Featured article stays centered. |

---

## 10. Dark mode / preview

| Field | Value |
|-------|-------|
| **Dark mode background override** | ${escMd(val(d.darkBgOverride)) || '*(leave blank to use template defaults)*'} |
| **Dark mode text override** | ${escMd(val(d.darkTextOverride))} |
| **Minimum contrast ratio target** | ${d.contrastTarget} |

---

## 11. Element mapping *(reference)*

| Design token | \`data-element\` examples |
|--------------|-------------------------|
| Logo | \`logo\`, header \`<img>\` |
| Primary CTA | \`cta-primary\`, \`hero-cta\`, \`primary-cta\`, \`featured-cta\`, \`pricing-cta\`, \`promo-cta\` |
| Secondary CTA | \`cta-secondary\`, \`secondary-cta\` |
| Headings | \`header-kicker\`, \`header-title\`, \`launch-title\`, \`overview-heading\` |
| Body copy | \`launch-subtitle\`, \`overview-description\`, \`featured-body\` |
| Footer company | \`footer-company-name\` |
| Footer address | \`footer-address\` |
| Footer tagline | \`footer-tagline\` |
| Footer contact | \`footer-contact\` |
| Footer social | \`footer-social-facebook\`, \`footer-social-linkedin\`, … |
| Footer legal | \`footer-link-privacy\`, \`footer-link-terms\`, \`footer-link-unsubscribe\` |

---

## 12. Checklist before go-live

${CHECKLIST_ITEMS.map((item, i) => `- [${state.checklist[i] ? 'x' : ' '}] ${item}`).join('\n')}

---

*Exported from Brand Design Wizard on ${new Date().toLocaleDateString()}.*
`;
}

export function downloadDesignRules(state: DesignRulesState): void {
  const blob = new Blob([exportDesignRules(state)], { type: 'text/markdown;charset=utf-8' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'DESIGN_RULES.md';
  a.click();
  URL.revokeObjectURL(a.href);
}
